# Generated by Django 2.2.7 on 2019-11-08 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='specialization', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subbatch',
            fields=[
                ('subbatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('level', models.CharField(blank=True, choices=[('M', 'Masters'), ('U', 'UnderGraduate'), ('H', 'HighSchool'), ('F', 'Foundation'), ('N', 'Nurcher')], default='H', help_text='level of subbatch', max_length=1)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('batch', models.ManyToManyField(help_text='contents to be taught', to='accounts.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='media/')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, editable=False, null=True)),
                ('program', models.CharField(blank=True, choices=[('M', 'Masters'), ('U', 'UnderGraduate'), ('H', 'HighSchool'), ('F', 'Foundation'), ('N', 'Nurcher')], default='H', help_text='user qualification', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('total_upvote', models.IntegerField(blank=True, null=True)),
                ('total_view', models.IntegerField(blank=True, null=True)),
                ('is_mentor', models.BooleanField(default=False, verbose_name='want to become a mentor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Ssconnector',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('S', 'Student'), ('M', 'Mentor'), ('O', 'Organizer')], default='S', help_text='user role', max_length=1)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Student')),
                ('subbatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Subbatch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Subject'),
        ),
    ]
