# Generated by Django 2.2.7 on 2019-11-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quotes_id', models.AutoField(primary_key=True, serialize=False)),
                ('quotes', models.TextField(default='No matter what you dream, It will come true.', help_text='enter your thoughts of the day', max_length=255, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
