# Generated by Django 2.2.7 on 2019-11-09 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
