# Generated by Django 2.2.7 on 2019-11-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_quotes_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ['created_time']},
        ),
    ]
