# Generated by Django 2.2.7 on 2019-11-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191109_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(blank=True, help_text='author of quotes', max_length=55),
        ),
    ]
