# Generated by Django 2.2.7 on 2019-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_quotes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='describe_yourself',
            field=models.TextField(blank=True, help_text='describe_yourself', max_length=255),
        ),
    ]
